---
- import_tasks: managePackages.yml
  tags:
  - aspects_iptables
  - aspects_iptables_package_install

- import_tasks: iptables.yml
  when: ( aspects_iptables_enabled and
          not (
            (
              ansible_distribution == "Ubuntu" and
              ansible_distribution_version == "16.04"
            ) or (
              ansible_distribution == "Debian" and
              ansible_distribution_release == "stretch"
            )
          )
        )
  tags:
  - aspects_iptables

- name: "Import Xenial, Bionic, and Stretch tasks."
  import_tasks: iptables1604.yml
  when: aspects_iptables_enabled and
        (
          (
            ansible_distribution == "Ubuntu" and
            ansible_distribution_version == "16.04"
          ) or (
            ansible_distribution == "Ubuntu" and
            ansible_distribution_version == "18.04"
          ) or (
            ansible_distribution == "Debian" and
            ansible_distribution_release == "stretch"
          )
        )
  tags:
  - aspects_iptables

- name: Disable and purge the packages and configuration installed by this role.
  when: aspects_iptables_disable_and_purge and not aspects_iptables_enabled
  import_tasks: disableAndPurge.yml
  tags:
    - aspects_iptables
    - aspects_iptables_disable_and_purge