---
# Create and apply iptables rules
- name: Xenial - Template iptables v4 rules file.
  template:
    src: "iptablesv4rules.j2"
    dest: "/etc/iptables/rules.v4"
    mode: 0644
    owner: 0
    group: 0
  notify: Xenial restore iptables
  tags:
  - aspects_iptables
