---
# tasks file for aspects_iptables_packages
- name: Debian - Install python-apt for use with ansible apt modules.
  when: ansible_os_family == "Debian"
  apt: pkg=python-apt state=latest update_cache="yes" cache_valid_time="86400"
  tags:
    - aspects_iptables
    - aspects_iptables_packages

- name: Debian - Set default packages state with apt
  when: ansible_os_family == "Debian" and item.value.state != 'default' and item.value.state != 'purged' and item.value.Debian is defined
  apt: pkg={{ item.value.Debian }} state={{ item.value.state }} update_cache="yes" cache_valid_time="86400"
  with_dict: aspects_iptables_packages
  tags:
    - aspects_iptables
    - aspects_iptables_packages

- name: Debian - Purge packages with state="purged" with apt
  when: ansible_os_family == "Debian" and item.value.state == 'purged' and item.value.Debian is defined
  apt: pkg={{ item.value.Debian }} state=absent purge=yes update_cache="yes" cache_valid_time="86400"
  with_dict: aspects_iptables_packages
  tags:
    - aspects_iptables
    - aspects_iptables_packages

- name: RedHat - Set default packages state with yum
  when: ansible_os_family == "RedHat" and item.value.state != 'default' and item.value.state != 'purged' and item.value.RedHat is defined
  yum: name={{ item.value.RedHat }} state={{ item.value.state }}
  with_dict: aspects_iptables_packages
  tags:
    - aspects_iptables
    - aspects_iptables_packages

- name: RedHat - Remove packages with state="purged" with yum
  when: ansible_os_family == "RedHat" and item.value.state == 'purged' and item.value.RedHat is defined
  yum: name={{ item.value.RedHat }} state=absent
  with_dict: aspects_iptables_packages
  tags:
    - aspects_iptables
    - aspects_iptables_packages

- name: Suse - Set default packages state with Zypper
  when: ansible_os_family == "Suse" and item.value.state != 'default' and item.value.state != 'purged' and item.value.Suse is defined
  zypper: name={{ item.value.Suse }} state={{ item.value.state }}
  with_dict: aspects_iptables_packages
  tags:
    - aspects_iptables
    - aspects_iptables_packages

- name: Suse - Remove packages with state="purged" with Zypper
  when: ansible_os_family == "Suse" and item.value.state == 'purged' and item.value.Suse is defined
  zypper: name={{ item.value.Suse }} state=absent
  with_dict: aspects_iptables_packages
  tags:
    - aspects_iptables
    - aspects_iptables_packages