---
- name: Debian - Install python-apt for use with ansible apt modules.
  when: ansible_os_family == "Debian" or ansible_os_family == "Linuxmint"
  apt:
    pkg: python-apt
    state: latest
    update_cache: "yes"
    cache_valid_time: "86400"
  tags:
    - aspects_iptables
    - aspects_iptables_package_install

- name: Debian - Install iptables packages with apt
  when:
    (ansible_os_family == "Debian" or ansible_os_family == "Linuxmint") and
    item.value.state != 'default' and
    item.value.state != 'purged' and
    item.value.Debian is defined
  apt:
    pkg: "{{ item.value.Debian }}"
    state: "{{ item.value.state }}"
    update_cache: "yes"
    cache_valid_time: "86400"
  with_dict: "{{ aspects_iptables_packages }}"
  tags:
    - aspects_iptables
    - aspects_iptables_package_install

- name: RedHat - Install iptables packages with yum
  when:
    ansible_os_family == "RedHat" and
    item.value.state != 'default' and
    item.value.state != 'purged' and
    item.value.RedHat is defined
  yum:
    name: "{{ item.value.RedHat }}"
    state: "{{ item.value.state }}"
  with_dict: "{{ aspects_iptables_packages }}"
  tags:
    - aspects_iptables
    - aspects_iptables_package_install

- name: CentOS 7 - Remove firewalld so it will not interfere with iptables
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  yum:
    name: "firewalld"
    state: "absent"
  tags:
    - aspects_iptables
    - aspects_iptables_package_install
